parameters:
    locale: 'en'
    app.notifications.email_sender: anonymous@example.com
    youtube.api.key: '%env(YOUTUBE_API_KEY)%'

services:
    _defaults:
        autowire: true 
        autoconfigure: true
        bind:
            array $enabledLocales: '%kernel.enabled_locales%'
            string $defaultLocale: '%locale%'
            string $apiKey: '%env(YOUTUBE_API_KEY)%'

    App\Service\YoutubeService:
        arguments:
            $apiKey: 'AIzaSyDdLMEkkqSLu-oimwOO2fvS1CmRI2z1Nas'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'